[profile.default]
src = 'packages/foundry/contracts'
out = 'packages/foundry/out'
test = 'packages/foundry/test'
libs = ['packages/foundry/lib']
broadcast = 'broadcast'
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
  "@ens-contracts=node_modules/@ensdomains/ens-contracts/contracts",
  "@openzeppelin=node_modules/@openzeppelin",
  "forge-std=node_modules/forge-std/src",
  "solidity-bytes-utils=node_modules/solidity-bytes-utils/contracts",
]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrumSepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }


[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"
contract_new_lines = true
multiline_func_header = "all"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
